services:
    ekline-migrations:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: ekline-migrations
        env_file:
            - ./backend/.env
        command: sh -c "node scripts/wait-for-db.js && npm run migrate:up"
        depends_on:
            ekline-db:
                condition: service_healthy
        networks:
            - ekline-network
        volumes:
            - ./backend:/app
            - /app/node_modules
        restart: "no"

    ekline-backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: ekline-backend
        env_file:
            - ./backend/.env
        ports:
            - "4000:4000"
        depends_on:
            - ekline-db
            - ekline-redis
            - ekline-migrations
        networks:
            - ekline-network
        volumes:
            - ./backend:/app
            - /app/node_modules

    ekline-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: ekline-frontend
        env_file:
            - ./frontend/.env
        ports:
            - "3000:3000"
        depends_on:
            - ekline-backend
        networks:
            - ekline-network
        volumes:
            - ./frontend:/app
            - /app/node_modules

    ekline-db:
        image: postgres:16-alpine
        container_name: ekline-db
        restart: unless-stopped
        env_file:
            - ./backend/.env
        ports:
            - "5432:5432"
        volumes:
            - ekline_postgres_data:/var/lib/postgresql/data
        networks:
            - ekline-network
        healthcheck:
            test: ["CMD-SHELL", "pgrep postgres || exit 1"]
            interval: 5s
            timeout: 5s
            retries: 5

    ekline-redis:
        image: redis:7-alpine
        container_name: ekline-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - ekline-network

networks:
    ekline-network:

volumes:
    ekline_postgres_data:
