version: "3.9"

services:
    ekline-backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: ekline-backend
        env_file:
            - .env
        ports:
            - "4000:4000"
        depends_on:
            ekline-db:
                condition: service_healthy
            ekline-redis:
                condition: service_started
        networks:
            - ekline-network
        volumes:
            - ./backend:/app
            - /app/node_modules

    ekline-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: ekline-frontend
        ports:
            - "3000:3000"
        depends_on:
            - ekline-backend
        networks:
            - ekline-network
        volumes:
            - ./frontend:/app
            - /app/node_modules

    ekline-db:
        image: postgres:16-alpine
        container_name: ekline-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ekline_postgres_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 5s
            timeout: 3s
            retries: 5
        networks:
            - ekline-network

    ekline-redis:
        image: redis:7-alpine
        container_name: ekline-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - ekline-network

networks:
    ekline-network:

volumes:
    ekline_postgres_data:
